### ISSUE TITLE
Reorganise `poses_accessor.py`

### ISSUE THREAD

**Issue by lochhh** [neuroinformatics-unit/movement#118]
> Should we also rename the class itself to `MoveAccessor`? And the file accordingly to `move_accessor.py`?
I was also thinking of moving this out of the io folder into `movement/move_accessor.py` (since it will no longer have strictly io functionalities).

_Originally posted by @niksirbi in https://github.com/neuroinformatics-unit/movement/pull/106#discussion_r1495028568_
  
```[tasklist]
### Tasks
- [x] Rename `poses_accessor.py` to `move_accessor.py`
- [x] Move `move_accessor.py` out of the io folder into `movement/move_accessor.py`
- [x] Rename `PoseAccessor` class to `MoveAccessor`
- [x] Rename `poses` accessor to `move`
- [ ] https://github.com/neuroinformatics-unit/movement/issues/119
- [ ] https://github.com/neuroinformatics-unit/movement/issues/120
```
