### ISSUE TITLE
Ability to export poses in various formats

### ISSUE THREAD

**Issue by niksirbi** [neuroinformatics-unit/movement#13]
In particular, either `DeepLabCut` or `SLEAP`. This would be useful for converting between formats, especially for downstream analysis tools that are only made for one specific format.

```[tasklist]
### Tasks
- [ ] https://github.com/neuroinformatics-unit/movement/pull/33
- [ ] https://github.com/neuroinformatics-unit/movement/issues/39
- [ ] https://github.com/neuroinformatics-unit/movement/issues/46
- [ ] https://github.com/neuroinformatics-unit/movement/issues/45
- [ ] https://github.com/neuroinformatics-unit/movement/issues/23
```

**Comment by niksirbi** [comment]
In PR #33  I have included a `save_poses.to_dlc_file()` function that exports data in DeepLabCut format (see however #39).

Apart from that we need additional export options:
- a movement-native format, suitable for xarray objects (most likely zarr)
- `save_poses.to_sleap_file()` that probably writes a SLEAP analysis.h5 file
- ndx-pose NWB? see #23

**Comment by niksirbi** [comment]
I will keep this issue open to have an overview of the overall progress on exporting functionalities.
Meanwhile, I'm creating separate issues for each export format:

**Comment by niksirbi** [comment]
Since this is a central goal of movement, and will always be, so it doesn't make sense to keep this tasklist forever open.
Therefore, we decided to close it, but keep the individual issues open.
