### ISSUE TITLE
Refactor Makefiles

### ISSUE THREAD

**Issue by lochhh** [neuroinformatics-unit/movement#329]
```[tasklist]
### Tasks
- [x] Drop `--keep-going`. From Sphinx 8.1 this option is always enabled
- [x] Simplify `make_api_index` directory crawl
- [x] Update windows makefile to match unix
```
