### ISSUE TITLE
Restructure docs informed by the diataxis framework

### ISSUE THREAD

**Issue by niksirbi** [neuroinformatics-unit/movement#70]
Within the team, we discussed the [diataxis](https://diataxis.fr/) systematic approach to documentation, and we agreed that the distinctions it makes between "tutorials", "how to guides", "reference", and "explanation" are sensible and useful.

We want to restructure the docs to better reflect this approach. This doesn't necessarily mean having the above 4 sections explicitly. But for example, we could start by rewriting the current "getting started" and "example" in a way that there is a clear split between:
- an entry-level "quickstart"/"walkthrough" tutorial that familiarises users to the basics of movement, via learning-by-doing.
- "how-to-guides" for specific real-world tasks, such as "loading data from SLEAP".

```[tasklist]
### Tasks
- [ ] https://github.com/neuroinformatics-unit/movement/issues/140
- [ ] https://github.com/neuroinformatics-unit/movement/issues/69
- [ ] https://github.com/neuroinformatics-unit/movement/issues/284
```

**Comment by sfmig** [comment]
We decide to close this meta issue because it feels too broad / a forever issue.

We will track this work with the individual issues instead.
